% Example on the use of Helsinki BEM Framework kernel:
% 4-shell MEG model.
% 
% The example uses meshes from Head 1 of (Stenroos and Nummenmaa, 2016),
% remeshed by me based on sample data of SimNIBS toolbox. If you wish to use the
% meshes or model for something, please contact me first.
%
% (c) Matti Stenroos 2016
clear
%add BEM framework paths --- depends on version, see the examples included
%in your delivery package!
addpath ./hbf_calc
addpath ./hbf_mesh
% load example data for meshes, coils, and
% sources.
loaddir='~/bioem/exampledata/sample4/';
load(strcat(loaddir,'bmeshes-m40-50-50-60-70.mat'));%bmeshes
bmeshes=bmeshes.meshes;
load(strcat(loaddir,'coils-cmeg306.mat'));%coils
load(strcat(loaddir,'sources-sfs30.mat'));%sources
Nmeshes=length(bmeshes);
success=zeros(Nmeshes,1);
for M=1:Nmeshes;
    [bmeshes{M},success(M)]=hbf_CorrectTriangleOrientation(bmeshes{M});
end

% status=cell(Nmeshes,1);
% for M=1:Nmeshes;
%     [status{M}]=hbf_CheckMesh(bmeshes{M});
% end

%% ------------------------------------------------------------------------
% Hey, ho, let's go!

starttime=clock;
% Build double-layer matrices for the BEM
D=hbf_BEMOperatorsPhi_LC(bmeshes);
% Build matrices for integrating the magnetic field due to volume currents 
DB=hbf_BEMOperatorsB_Linear(bmeshes,coils);
cratio=50;
c_brain=.33;c_csf=1.79;c_skull=c_brain/cratio;c_skin=.33;
ci=[c_brain,c_brain,c_csf,c_skull,c_skin];%conductivity inside each surface --- remember the order!
co=[c_csf,c_csf,c_skull,c_skin,0];%conductivity outside each surface --- remember the order!

% Build BEM transfer matrix for potential using the isolated source
% approach, isolation set to surface 3 = inner skull
Tphi_full=hbf_TM_Phi_LC_ISA2(D,ci,co,3);
% ...and make a transfer matrix for the magnetic field generated by the
% volume currents.
TBvol=hbf_TM_Bvol_Linear(DB,Tphi_full,ci,co);

%%
% compute lead field matrices for normally oriented dipoles
LFMstarttime=clock;
LFM_Mdir{1}=hbf_LFM_B_LC_dir(bmeshes,coils,TBvol,sources.spos{1},sources.sdir{1});
LFM_Mdir{2}=hbf_LFM_B_LC_dir(bmeshes,coils,TBvol,sources.spos{2},sources.sdir{2});
fprintf('Time for LFM computation was %ds.\n',round(etime(clock,LFMstarttime)));
fprintf('Total time was %ds.\n',round(etime(clock,starttime)));

% compute lead field matrices for xyz unit dipole triplets
LFM_Mxyz{1}=hbf_LFM_B_LC_xyz(bmeshes,coils,TBvol,sources.spos{1});
LFM_Mxyz{2}=hbf_LFM_B_LC_xyz(bmeshes,coils,TBvol,sources.spos{2});
