function [ surface_points ] = mesh_getelectrode(filename, skin_f, skin_v, proj)
%This function is used to load an -elc-trans.mat file generated by the
%generate_elctrans bash script.
if nargin < 4
    proj = true;
end

load(filename, 'dig', 'trans')

% apply the transformation matrix
dig = (trans * [dig, ones(size(dig, 1), 1)]')';
dig(:,4) = [];

% scale dig coordinates to mm units as in the bem surfaces 
dig = dig * 1000;

% project the electrodes to the skin surface 
if proj
    [ ~, surface_points ] = point2trimesh('Faces', skin_f, 'Vertices', skin_v, 'QueryPoints', dig);
else
    surface_points = dig;
end

end

